using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StatsManager
{
    public enum IndicatorType
    {
        None,
        SMA,
        DEMA,
        KAMA,
        SMACROSS,
        MACD,
        RSI,
        EMA,
        EMACROSS,
        HHLL,
        MISC,
        HHHC,
        ACCUMULATIONDISTRIBUTION,
        SUPPORT_RESISTANCE,
        WILLIAMSR,
        STOCHASTIC_OSCILLATOR,
        MIN,
        MAX,
        BBANDS,
        LINEARREG,
        LINEARREG_SLOPE,
        LINEARREG_ANGLE,
        LINEARREG_INTERCEPTOR,
        MOM,
        TRIPLE_TOP,
        SAR,
        CDL_THREE_BLACK_CROWS,
        CDL_THREE_WHITE_SOLDIERS,
        CDL_TWO_CROWS,
        CDL_ABANDON_BABY,
        CDL_THREE_OUTSIDE_UP_DOWN,
        CDL_THREE_INSIDE_UP_DOWN,
        CDL_THREE_STARS_SOUTH,
        CDL_ADVANCE_BLOCK,
        CDL_BREAK_AWAY,
        CDL_CLOSING_MARUBOZU,
        CDL_CONCEALING_BABY_SWALLO,
        CDL_COUNTER_ATTACK,
        CDL_DOJI,
        CDL_HAMMER,
        CDL_HANGING_MAN,
        CDL_HARAMI,
        CDL_HARAMI_CROSS,
        CDL_HIGH_WAVE,
        CDL_HIKKAKE,
        CDL_HIKKAKE_MODIFIED,
        CDL_HOMING_PEGION,
        CDL_IDENTICAL_THREE_CROWS,
        CDL_IN_NECK,
        CDL_INVERTED_HAMMER,
        CDL_KICKER,
        CDL_KICKER_BY_LENGTH,
        CDL_LADDER_BOTTOM,
        CDL_LONG_LEGGED_DOJI,
        CDL_LONG_LINE,
        CDL_MARBOZU,
        CDL_MATCHING_LOW,
        CDL_MATHOLD,
        CDL_MORNING_DOJI_STAR,
        CDL_MORNING_STAR,
        CDL_ON_NECK,
        CDL_PIERCING,
        CDL_RICKSHAW_MAN,
        CDL_RISE_FALL_3_METHODS,
        CDL_SEPERATING_LINES,
        CDL_ENGULF,
        CDL_SHOOTING_STAR,
        CDL_SHORT_LINE,
        CDL_SPINNING_TOP,
        CDL_STALLED,
        CDL_STICK_SANDWICH,
        CDL_TAKURI,
        CDL_TASKI_GAP,
        CDL_THRUST,
        CDL_TRI_STAR,
        CDL_UNIQUE_3_RIVER,
        UPSIDE_GAP_TWO_CROWS,
        CDL_UPSIDE_DOWNSIDE_GAP_3_METHODS,
        VOLGROWTH,
        INV_HEAD_SHOULDERS,
        MAX_NONE
    }

    public enum TrendType
    {
        None,
        BULL,
        BEAR,
        CONSOLIDATION
    }
}
